"""Agent 12: Documentation Writer.

Generates comprehensive documentation, API reference guides, and markdown manuals.
Operates at Permission Tier 0 (Safe Read / Documentation).
"""

from __future__ import annotations

import logging
from typing import Any, Dict
from agents.base import BaseAgent, AgentInput, AgentOutput

logger = logging.getLogger("max.agents.doc_writer")


class DocWriter(BaseAgent):
    name = "DocWriter"
    description = "Generates technical documentation, API guides, and markdown manuals."
    permission_tier = 0  # Safe Read

    def _execute(self, input_data: AgentInput) -> AgentOutput:
        desc = input_data.task_description
        logger.info("DocWriter generating documentation for: %s", desc)

        doc_type = input_data.parameters.get("type", "markdown")
        title = input_data.parameters.get("title", desc)

        content = (
            f"# {title}\n\n"
            f"## Overview\n"
            f"{desc}\n\n"
            f"## Usage\n"
            f"```python\n"
            f"# Example usage\n"
            f"```\n\n"
            f"## API Reference\n"
            f"Automated documentation generated by DocWriter.\n"
        )

        return AgentOutput(
            success=True,
            result=f"Documentation '{title}' generated successfully",
            artifacts={"title": title, "type": doc_type, "content": content},
        )
