"""
MAX OS — Permission Manager (Step 2.7).
Principle #2 & D3: auto/confirm/blocked tier enforcement is immune to user phrasing.
A gate that can be skipped by rephrasing a request was never a real gate.
"""

from __future__ import annotations

import enum
import sqlite3
import uuid
from dataclasses import dataclass
from pathlib import Path
from typing import Dict, Optional, Set

DEFAULT_DB_PATH = Path(__file__).parent.parent / "max_state.db"


from core.errors import GateRequiredError


class PermissionTier(str, enum.Enum):
    AUTO = "auto"
    CONFIRM = "confirm"
    BLOCKED = "blocked"


# Default agent permission tiers
DEFAULT_AGENT_PERMISSIONS: Dict[str, PermissionTier] = {
    "calendar": PermissionTier.AUTO,
    "notes": PermissionTier.AUTO,
    "coding": PermissionTier.CONFIRM,
    "deploy": PermissionTier.CONFIRM,
    "database": PermissionTier.CONFIRM,
    "cloud_infra": PermissionTier.CONFIRM,
    "keyboard_credentials": PermissionTier.BLOCKED,
    "mouse_credentials": PermissionTier.BLOCKED,
}


@dataclass
class PermissionCheckResult:
    allowed: bool
    tier: PermissionTier
    reason: str
    requires_human_approval: bool = False


class PermissionManager:
    """
    Code-enforced Permission Manager.
    Tiers:
      - AUTO: executes immediately.
      - CONFIRM: strictly requires a verified approval token generated by an explicit human confirmation step.
      - BLOCKED: hard blocked by safety policy, cannot execute under any circumstance.
    Phrasing in the user prompt is intentionally ignored and cannot override permissions.
    """

    def __init__(self, db_path: Optional[Path | str] = None):
        self.db_path = Path(db_path) if db_path else DEFAULT_DB_PATH
        self._valid_approval_tokens: Set[str] = set()

    def grant_approval_token(self) -> str:
        """Generates and registers an approval token upon human confirmation."""
        token = f"approval-token-{uuid.uuid4()}"
        self._valid_approval_tokens.add(token)
        return token

    def revoke_approval_token(self, token: str) -> None:
        self._valid_approval_tokens.discard(token)

    def get_agent_tier(self, agent: str) -> PermissionTier:
        """Looks up default permission tier for agent."""
        if agent in DEFAULT_AGENT_PERMISSIONS:
            return DEFAULT_AGENT_PERMISSIONS[agent]

        if self.db_path.exists():
            try:
                conn = sqlite3.connect(str(self.db_path))
                conn.row_factory = sqlite3.Row
                cur = conn.cursor()
                row = cur.execute(
                    "SELECT default_permission FROM agent_registry WHERE agent_name = ?",
                    (agent,),
                ).fetchone()
                conn.close()
                if row and row["default_permission"]:
                    return PermissionTier(row["default_permission"])
            except Exception:
                pass

        return PermissionTier.CONFIRM

    def check_permission(
        self,
        agent: str,
        action: str,
        user_prompt: str = "",
        approval_token: Optional[str] = None,
    ) -> PermissionCheckResult:
        """
        Evaluates whether an action is permitted.
        Note: user_prompt is never parsed to bypass confirmation (Principle #2).
        """
        tier = self.get_agent_tier(agent)

        if tier == PermissionTier.BLOCKED:
            return PermissionCheckResult(
                allowed=False,
                tier=tier,
                reason=f"Action '{action}' on agent '{agent}' is hard-blocked by safety policy.",
                requires_human_approval=False,
            )

        if tier == PermissionTier.AUTO:
            return PermissionCheckResult(
                allowed=True,
                tier=tier,
                reason="Action allowed automatically.",
                requires_human_approval=False,
            )

        if tier == PermissionTier.CONFIRM:
            if approval_token and approval_token in self._valid_approval_tokens:
                return PermissionCheckResult(
                    allowed=True,
                    tier=tier,
                    reason="Human approval token verified.",
                    requires_human_approval=False,
                )
            return PermissionCheckResult(
                allowed=False,
                tier=tier,
                reason=f"Action '{action}' on agent '{agent}' requires human confirmation approval.",
                requires_human_approval=True,
            )

        return PermissionCheckResult(allowed=False, tier=tier, reason="Unknown permission tier.")
